### ISSUE TITLE
hotfix/employer-profile-upsert-error

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#221]
When resetting my local db I noticed I could not create an employer account. Getting a 400 bad request error on upsert. Also, the existing data doesn't load into edit profile inputs on `/edit-profile/employer/profile`

**Comment by gageberz** [comment]
userId is empty on upsert leading to the 400

edit: Spent quite a bit of time to get it to fill in the userId during page load, but no success, race condition issue, so for now the fix will just be upserting with the id set in the submit function.

Or, if preferred later, we can just not bother upserting userId, because there is no reason to do that when we are already calling session on the server side for their id, unless I'm missing something

**Comment by theGaryLarson** [comment]
https://www.watechwfcoalition.org/edit-profile/employer/profile

![Image](https://github.com/user-attachments/assets/b3ef9913-6ef6-4b3f-a8ca-b86a15aa6717)

The employer record is not being created but they employerId is being saved on session.

Two key errors:
![Image](https://github.com/user-attachments/assets/994df6aa-c8ce-4702-99bf-cb944f5af196)

![Image](https://github.com/user-attachments/assets/0e6a80f5-af46-469d-8585-4bb541d26f9f)

**Comment by theGaryLarson** [comment]
LGTM. Going to close this. Thanks Gage!
